name: counter
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  riverpod:
    path: ../../packages/riverpod

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_cli: ^0.0.3

dependency_overrides:
  flutter_riverpod:
    path: ../../packages/flutter_riverpod
  hooks_riverpod:
    path: ../../packages/hooks_riverpod
  riverpod:
    path: ../../packages/riverpod
  riverpod_cli:
    path: ../../packages/riverpod_cli

flutter:
  uses-material-design: true
