
name: riverpod_analyzer_plugin_loader
version: 8.0.6
description: This pubspec determines the version of the analyzer plugin to load.
environment:
  sdk: '>=2.12.0 < 3.0.0'
dependencies:
  riverpod_cli: ^0.0.3
dependency_overrides:
  riverpod_cli: 
    path: ../../
