name: codemod_riverpod
description: A migration package for riverpod changes.
version: 0.0.1
homepage: https://riverpod.dev
repository: https://github.com/rrousselGit/river_pod

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  codemod: ^0.2.0
  glob: ^1.2.0

dev_dependencies:
  test: any

executables:
  migrate: codemod_riverpod
